<?php

/*
 * @ccnRef: @theme_evagu/layout
 */
defined('MOODLE_INTERNAL') || die();
if (!isset($extraclasses)) {
    $extraclasses = [];
}
array_push($extraclasses, 'ccn_context_dashboard');
$bodyclasses = implode(' ', $extraclasses);
$bodyattributes = $OUTPUT->body_attributes($bodyclasses);
$templatecontext = [
    'lang_menu' => $langMenu,
    'sitename' => format_string($SITE->shortname, true, ['context' => context_course::instance(SITEID), 'escape' => false]),
    'output' => $OUTPUT,
    'ccnLogoUrl' => $ccnLogoUrl,
    'pageheading' => format_text($pageheading, FORMAT_HTML, array('filter' => true)),
    'sidepreblocks' => $blockshtml,
    'ccn_login' => $_ccnlogin,
    // 'ccn_registration' => $_ccnregistration,
    'ccn_activitynav' => $_ccnCourseSectionNav,
    'ccn_course_url' => $ccnCourseUrl,
    'ccn_dashboard_url' => $CFG->wwwroot . '/my',
    'ccn_globalsearch' => $_ccnglobalsearch,
    'ccn_globalsearch_navbar' => $_ccnglobalsearch_navbar,
    'ccn_librarylist' => $_ccnlibrarylist,
    'library_list_blocks' => $OUTPUT->blocks('library-list'),
    'has_library_list_blocks' => strpos($OUTPUT->blocks('library-list'), 'data-block=') !== false,
    'navbar_blocks' => $OUTPUT->blocks('navbar'),
    'has_navbar_blocks' => strpos($OUTPUT->blocks('navbar'), 'data-block=') !== false,
    'leftblocks' => $leftblocks,
    'hasblocks' => $hasblocks,
    'hasleftblocks' => $hasleftblocks,
    'hassideblocks' => $hassideblocks,
    'sidebar_single' => $sidebar_single,
    'sidebar_single_left' => $sidebar_single_left,
    'sidebar_single_right' => $sidebar_single_right,
    'sidebar_left' => $sidebar_left,
    'sidebar_right' => $sidebar_right,
    'sidebar_double' => $sidebar_double,
    'sidebar_none' => $sidebar_none,
    'participant_user_profile' => $userProfileFromCourseParticipants,
    'bodyattributes' => $bodyattributes,
    'headerlogo1' => $headerlogo1,
    'headerlogo2' => $headerlogo2,
    'headerlogo3' => $headerlogo3,
    'headerlogo4' => $headerlogo4,
    'headerlogo_mobile' => $headerlogo_mobile,
    'footerlogo1' => $footerlogo1,
    'heading_bg' => $heading_bg,
    'favicon' => $favicon,
    'regionmainsettingsmenu' => $regionmainsettingsmenu,
    'hasregionmainsettingsmenu' => !empty($regionmainsettingsmenu),
    'loginblocks' => $loginblocks,
    'hasloginblocks' => !empty($loginblocks),
    'searchblocks' => $searchblocks,
    'hassearchblocks' => !empty($searchblocks),
    'blocks_user_notifications' => $blocks_user_notifications,
    'blocks_user_messages' => $blocks_user_messages,
    'blocks_fullwidth_top' => $blocks_fullwidth_top,
    'blocks_fullwidth_bottom' => $blocks_fullwidth_bottom,
    'blocks_above_content' => $blocks_above_content,
    'has_blocks_above_content' => !empty($blocks_above_content),
    'blocks_below_content' => $blocks_below_content,
    'has_blocks_below_content' => !empty($blocks_below_content),
    'has_blocks_fullwidth_top' => !empty($blocks_fullwidth_top),
    'has_blocks_fullwidth_bottom' => !empty($blocks_fullwidth_bottom),
    'is_course' => $PAGE->bodyid == 'page-course-view-topics' || $PAGE->bodyid == 'page-course-view-tiles',
    'is_blog' => $PAGE->bodyid == 'page-blog-index',
    'is_frontpage' => $PAGE->bodyid == 'page-site-index',
    'courseid' => $courseid,
    'coursefullname' => $coursefullname,
    'courseshortname' => $courseshortname,
    'coursecategory' => $coursecategory,
    'coursesummary' => $coursesummary,
    'courseformat' => $courseformat,
    'coursecreated' => $coursecreated,
    'coursemodified' => $coursemodified,
    'coursestartdate' => $coursestartdate,
    'courseenddate' => $courseenddate,
    'numberofusers' => $numberofusers,
    'eva_facebook_url' => format_text(get_config('theme_evagu', 'eva_facebook_url'), FORMAT_HTML, array('filter' => true)),
    'eva_twitter_url' => format_text(get_config('theme_evagu', 'eva_twitter_url'), FORMAT_HTML, array('filter' => true)),
    'eva_instagram_url' => format_text(get_config('theme_evagu', 'eva_instagram_url'), FORMAT_HTML, array('filter' => true)),
    'eva_pinterest_url' => format_text(get_config('theme_evagu', 'eva_pinterest_url'), FORMAT_HTML, array('filter' => true)),
    'eva_dribbble_url' => format_text(get_config('theme_evagu', 'eva_dribbble_url'), FORMAT_HTML, array('filter' => true)),
    'eva_google_url' => format_text(get_config('theme_evagu', 'eva_google_url'), FORMAT_HTML, array('filter' => true)),
    'eva_youtube_url' => format_text(get_config('theme_evagu', 'eva_youtube_url'), FORMAT_HTML, array('filter' => true)),
    'eva_vk_url' => format_text(get_config('theme_evagu', 'eva_vk_url'), FORMAT_HTML, array('filter' => true)),
    'eva_500px_url' => format_text(get_config('theme_evagu', 'eva_500px_url'), FORMAT_HTML, array('filter' => true)),
    'eva_behance_url' => format_text(get_config('theme_evagu', 'eva_behance_url'), FORMAT_HTML, array('filter' => true)),
    'eva_digg_url' => format_text(get_config('theme_evagu', 'eva_digg_url'), FORMAT_HTML, array('filter' => true)),
    'eva_flickr_url' => format_text(get_config('theme_evagu', 'eva_flickr_url'), FORMAT_HTML, array('filter' => true)),
    'eva_foursquare_url' => format_text(get_config('theme_evagu', 'eva_foursquare_url'), FORMAT_HTML, array('filter' => true)),
    'eva_linkedin_url' => format_text(get_config('theme_evagu', 'eva_linkedin_url'), FORMAT_HTML, array('filter' => true)),
    'eva_medium_url' => format_text(get_config('theme_evagu', 'eva_medium_url'), FORMAT_HTML, array('filter' => true)),
    'eva_meetup_url' => format_text(get_config('theme_evagu', 'eva_meetup_url'), FORMAT_HTML, array('filter' => true)),
    'eva_snapchat_url' => format_text(get_config('theme_evagu', 'eva_snapchat_url'), FORMAT_HTML, array('filter' => true)),
    'eva_tumblr_url' => format_text(get_config('theme_evagu', 'eva_tumblr_url'), FORMAT_HTML, array('filter' => true)),
    'eva_vimeo_url' => format_text(get_config('theme_evagu', 'eva_vimeo_url'), FORMAT_HTML, array('filter' => true)),
    'eva_wechat_url' => format_text(get_config('theme_evagu', 'eva_wechat_url'), FORMAT_HTML, array('filter' => true)),
    'eva_whatsapp_url' => format_text(get_config('theme_evagu', 'eva_whatsapp_url'), FORMAT_HTML, array('filter' => true)),
    'eva_wordpress_url' => format_text(get_config('theme_evagu', 'eva_wordpress_url'), FORMAT_HTML, array('filter' => true)),
    'eva_weibo_url' => format_text(get_config('theme_evagu', 'eva_weibo_url'), FORMAT_HTML, array('filter' => true)),
    'eva_telegram_url' => format_text(get_config('theme_evagu', 'eva_telegram_url'), FORMAT_HTML, array('filter' => true)),
    'eva_moodle_url' => format_text(get_config('theme_evagu', 'eva_moodle_url'), FORMAT_HTML, array('filter' => true)),
    'eva_amazon_url' => format_text(get_config('theme_evagu', 'eva_amazon_url'), FORMAT_HTML, array('filter' => true)),
    'eva_slideshare_url' => format_text(get_config('theme_evagu', 'eva_slideshare_url'), FORMAT_HTML, array('filter' => true)),
    'eva_soundcloud_url' => format_text(get_config('theme_evagu', 'eva_soundcloud_url'), FORMAT_HTML, array('filter' => true)),
    'eva_leanpub_url' => format_text(get_config('theme_evagu', 'eva_leanpub_url'), FORMAT_HTML, array('filter' => true)),
    'eva_xing_url' => format_text(get_config('theme_evagu', 'eva_xing_url'), FORMAT_HTML, array('filter' => true)),
    'eva_bitcoin_url' => format_text(get_config('theme_evagu', 'eva_bitcoin_url'), FORMAT_HTML, array('filter' => true)),
    'eva_twitch_url' => format_text(get_config('theme_evagu', 'eva_twitch_url'), FORMAT_HTML, array('filter' => true)),
    'eva_github_url' => format_text(get_config('theme_evagu', 'eva_github_url'), FORMAT_HTML, array('filter' => true)),
    'eva_gitlab_url' => format_text(get_config('theme_evagu', 'eva_gitlab_url'), FORMAT_HTML, array('filter' => true)),
    'eva_forumbee_url' => format_text(get_config('theme_evagu', 'eva_forumbee_url'), FORMAT_HTML, array('filter' => true)),
    'eva_trello_url' => format_text(get_config('theme_evagu', 'eva_trello_url'), FORMAT_HTML, array('filter' => true)),
    'eva_weixin_url' => format_text(get_config('theme_evagu', 'eva_weixin_url'), FORMAT_HTML, array('filter' => true)),
    'eva_slack_url' => format_text(get_config('theme_evagu', 'eva_slack_url'), FORMAT_HTML, array('filter' => true)),
    'eva_copyright' => format_text(get_config('theme_evagu', 'eva_copyright'), FORMAT_HTML, array('filter' => true)),
    'footer_col_1_title' => format_text(get_config('theme_evagu', 'footer_col_1_title'), FORMAT_HTML, array('filter' => true)),
    'footer_col_1_body' => format_text(get_config('theme_evagu', 'footer_col_1_body'), FORMAT_HTML, array('filter' => true, 'noclean' => true)),
    'footer_col_2_title' => format_text(get_config('theme_evagu', 'footer_col_2_title'), FORMAT_HTML, array('filter' => true)),
    'footer_col_2_body' => format_text(get_config('theme_evagu', 'footer_col_2_body'), FORMAT_HTML, array('filter' => true, 'noclean' => true)),
    'footer_col_3_title' => format_text(get_config('theme_evagu', 'footer_col_3_title'), FORMAT_HTML, array('filter' => true)),
    'footer_col_3_body' => format_text(get_config('theme_evagu', 'footer_col_3_body'), FORMAT_HTML, array('filter' => true, 'noclean' => true)),
    'footer_col_4_title' => format_text(get_config('theme_evagu', 'footer_col_4_title'), FORMAT_HTML, array('filter' => true)),
    'footer_col_4_body' => format_text(get_config('theme_evagu', 'footer_col_4_body'), FORMAT_HTML, array('filter' => true, 'noclean' => true)),
    'footer_col_5_title' => format_text(get_config('theme_evagu', 'footer_col_5_title'), FORMAT_HTML, array('filter' => true)),
    'footer_col_5_body' => format_text(get_config('theme_evagu', 'footer_col_5_body'), FORMAT_HTML, array('filter' => true, 'noclean' => true)),
    'footer_menu' => format_text(get_config('theme_evagu', 'footer_menu'), FORMAT_HTML, array('filter' => true)),
    'footer_column_1' => $footer_column_1,
    'footer_column_2' => $footer_column_2,
    'footer_column_3' => $footer_column_3,
    'footer_column_4' => $footer_column_4,
    'footer_column_5' => $footer_column_5,
    'footer_col_1_class' => $footer_col_1_class,
    'footer_col_2_class' => $footer_col_2_class,
    'footer_col_3_class' => $footer_col_3_class,
    'footer_col_4_class' => $footer_col_4_class,
    'footer_col_5_class' => $footer_col_5_class,
    'cta_text' => format_text(get_config('theme_evagu', 'cta_text'), FORMAT_HTML, array('filter' => true)),
    'cta_link' => format_text(get_config('theme_evagu', 'cta_link'), FORMAT_HTML, array('filter' => true)),
    'cta_icon' => ($ccnIcon = get_config('theme_evagu', 'cta_icon_ccn_icon_class')) ? $ccnIcon : 'flaticon-megaphone',
    'email_address' => format_text(get_config('theme_evagu', 'email_address'), FORMAT_HTML, array('filter' => true)),
    'phone' => format_text(get_config('theme_evagu', 'phone'), FORMAT_HTML, array('filter' => true)),
    'custom_css' => $custom_css,
    'custom_css_dashboard' => $custom_css_dashboard,
    'custom_js' => $custom_js,
    'custom_js_dashboard' => $custom_js_dashboard,
    'display_library_list' => $display_library_list,
    'logotype' => $logotype,
    'logo_image' => $logo_image,
    'logo' => $logo,
    'logotype_footer' => $logotype_footer,
    'logo_image_footer' => $logo_image_footer,
    'logo_footer' => $logo_footer,
    'user_profile_picture' => new moodle_url('/user/pix.php/' . $USER->id . '/f1.jpg'),
    'profile_icon_username' => $ccnProfileIconUsername,
    'user_username' => $USER->username,
    'user_firstname' => $USER->firstname,
    'user_lastname' => $USER->lastname,
    'user_email' => $USER->email,
    'user_language' => $USER->lang,
    'user_id' => $USER->id,
    'isloggedin' => $isloggedin == 'TRUE',
    'notloggedin' => $isloggedin == 'FALSE',
    'signup_is_enabled' => $signup_is_enabled == true,
    'signup_is_disabled' => $signup_is_enabled == false,
    'header_1' => $headertype == 1,
    'footer_1' => $footertype == 1,
    'breadcrumb_default' => $breadcrumb_style == 0,
    'breadcrumb_m' => $breadcrumb_style == 1,
    'breadcrumb_s' => $breadcrumb_style == 2,
    'breadcrumb_xs' => $breadcrumb_style == 3,
    'breadcrumb_hidden' => $breadcrumb_style == 4,
    'breadcrumb_classes' => $breadcrumb_classes,
    'breadcrumb_clip_dash' => $breadcrumb_clip_dash,
    'preloader_load' => $preloader_duration == 0,
    'preloader_ready' => $preloader_duration == 1,
    'preloader_5' => $preloader_duration == 2,
    'preloader_4' => $preloader_duration == 3,
    'preloader_3' => $preloader_duration == 4,
    'preloader_2' => $preloader_duration == 5,
    'preloader_disable' => $preloader_duration == 6,
    'headertype_frontpage_only' => FALSE,
    'headertype_all_pages' => TRUE,
    'header_search_icon' => $header_search == 0,
    'header_search_bar' => $header_search == 1,
    'header_login_popup' => $header_login == 0,
    'header_login_link' => $header_login == 1,
    'back_to_top' => $back_to_top == 0,
    // 'dashboard_sticky_header' => $dashboard_sticky_header == 0,
    'logo_styles' => $logo_styles,
    'logo_styles_footer' => $logo_styles_footer,
    'gmaps_key' => get_config('theme_evagu', 'gmaps_key'),
    'messages_link' => $messages_link,
    'profile_link' => $profile_link,
    'preferences_link' => $preferences_link,
    'grades_link' => $grades_link,
    'dash_header_white' => get_config('theme_evagu', 'dashboard_header') == 1,
    'dash_tabs' => $dash_tablet_count != 0,
    'dash_tab_col_class' => $dash_tab_col_class,
    'dash_tablet_1' => $dash_tablet_1,
    'dash_tablet_1_title' => format_text($dash_tablet_1_title, FORMAT_HTML, array('filter' => true)),
    'dash_tablet_1_subtitle' => format_text($dash_tablet_1_subtitle, FORMAT_HTML, array('filter' => true)),
    'dash_tablet_1_link' => $dash_tablet_1_link,
    'dash_tablet_1_icon' => $dash_tablet_1_icon,
    'dash_tablet_2' => $dash_tablet_2,
    'dash_tablet_2_title' => format_text($dash_tablet_2_title, FORMAT_HTML, array('filter' => true)),
    'dash_tablet_2_subtitle' => format_text($dash_tablet_2_subtitle, FORMAT_HTML, array('filter' => true)),
    'dash_tablet_2_link' => $dash_tablet_2_link,
    'dash_tablet_2_icon' => $dash_tablet_2_icon,
    'dash_tablet_3' => $dash_tablet_3,
    'dash_tablet_3_title' => format_text($dash_tablet_3_title, FORMAT_HTML, array('filter' => true)),
    'dash_tablet_3_subtitle' => format_text($dash_tablet_3_subtitle, FORMAT_HTML, array('filter' => true)),
    'dash_tablet_3_link' => $dash_tablet_3_link,
    'dash_tablet_3_icon' => $dash_tablet_3_icon,
    'dash_tablet_4' => $dash_tablet_4,
    'dash_tablet_4_title' => format_text($dash_tablet_4_title, FORMAT_HTML, array('filter' => true)),
    'dash_tablet_4_subtitle' => format_text($dash_tablet_4_subtitle, FORMAT_HTML, array('filter' => true)),
    'dash_tablet_4_link' => $dash_tablet_4_link,
    'dash_tablet_4_icon' => $dash_tablet_4_icon,
    'display_course_content' => $display_course_content == 1,
    'incourse_layout_dashboard' => $incourse_layout_dashboard == 1,
    'disable_stricky_dashboard' => $dashboard_scroll_header == 1,
    'dashboard_scroll_drawer' => $dashboard_scroll_drawer == 1,
    // 'dashboard_drawer_navigation' => $dashboard_left_drawer != (1 || 2),
    'dashboard_nav_user' => $dashboard_left_drawer != (1 || 2 || 3),  /* Theme Setting equals '0' */
    'dashboard_nav_flat' => $dashboard_left_drawer == 3,
    'disable_dashboard_drawer' => $dashboard_left_drawer == 2 || ($dashboard_left_drawer == 1 && !$sidebar_left),
    'incourse' => $incourse == 1,
    'in_course_activity' => $inCourseActivity,
    'show_course_start' => $showCourseStartDate != 1,
    'show_course_category' => $showCourseCategory != 1,
    // 'user_profile_layout_dashboard' => $user_profile_layout_dashboard == 1,
    'social_target_href' => $social_target_href,
    'if_user_navigation_icon' => get_config('theme_evagu', 'navigation_icon_visibility') != 1,
    'if_user_notification_icon' => get_config('theme_evagu', 'notification_icon_visibility') != 1,
    'if_user_messages_icon' => get_config('theme_evagu', 'messages_icon_visibility') != 1,
    'if_user_dark_mode_icon' => get_config('theme_evagu', 'dark_mode_icon_visibility') != 1,
    'user_navigation_icon' => ($ccnIcon = get_config('theme_evagu', 'navigation_icon_ccn_icon_class')) ? $ccnIcon : 'flaticon-settings',
    'user_notification_icon' => ($ccnIcon = get_config('theme_evagu', 'notification_icon_ccn_icon_class')) ? $ccnIcon : 'flaticon-alarm',
    'user_messages_icon' => ($ccnIcon = get_config('theme_evagu', 'messages_icon_ccn_icon_class')) ? $ccnIcon : 'flaticon-speech-bubble',
    'user_dark_mode_icon' => ($ccnIcon = get_config('theme_evagu', 'dark_mode_icon_ccn_icon_class')) ? $ccnIcon : 'ccn-flaticon-hide',
    'show_settings_controls' => $ccn_page_settings_controls == 1,
    'if_breadcrumb_title' => get_config('theme_evagu', 'breadcrumb_title') != 1,
    'if_breadcrumb_trail' => get_config('theme_evagu', 'breadcrumb_trail') != 1,
    'evagu_focus_sidebar' => !empty(get_config('theme_evagu', 'evagu_focus_sidebar')) && get_config('theme_evagu', 'evagu_focus_sidebar') === '1' ? false : true,
    'lang_menu_icons' => !empty(get_config('theme_evagu', 'language_menu')) && get_config('theme_evagu', 'language_menu') === '1' ? false : true,
    'is_4' => (int) $ccnMdlVersion >= 400 ? true : false
];
if ((int) $ccnMdlVersion >= 400) {
    $templatecontext['primarymoremenu'] = $primarymenu['moremenu'];
    $templatecontext['secondarymoremenu'] = $secondarynavigation ?: false;
    $templatecontext['eithermoremenu'] = !empty($primarymenu['moremenu']) || $secondarynavigation ? true : false;
    $templatecontext['mobileprimarynav'] = $primarymenu['mobileprimarynav'];
    $templatecontext['headercontent'] = $headercontent;
    $templatecontext['overflow'] = $overflow;
    $templatecontext['addblockbutton'] = $addblockbutton;
}
$PAGE->requires->jquery();
$ccnLcVbCollection = array(
    'eva_about_1',
    'eva_about_2',
    'eva_about_3',
    'eva_about_4',
    'eva_about_databases',
    'eva_abouteva',
    'eva_abouteva_cards',
    'eva_abouteva_info',
    'eva_accordion',
    'eva_accordion2',
    'eva_banner',
    'eva_banner_slider',
    'eva_blog_list',
    'eva_blog_recent',
    'eva_blog_recent_list',
    'eva_blog_recent_slider',
    'eva_boxes',
    'eva_cards_database',
    'eva_cards_post_internship',
    'eva_catalogo',
    'eva_cen_geral',
    'eva_cf_rating',
    'eva_contact_form',
    'eva_continuing_education_b1',
    'eva_continuing_education_b2',
    'eva_continuing_education_b3',
    'eva_continuing_education_cicles',
    'eva_continuing_education_news',
    'eva_course_details',
    'eva_course_features',
    'eva_course_grid',
    'eva_course_grid_2',
    'eva_course_grid_3',
    'eva_course_info',
    'eva_course_instructor',
    'eva_course_intro',
    'eva_course_list',
    'eva_course_overview',
    'eva_course_rating',
    'eva_courses_slider',
    'eva_custom_html',
    'eva_event_body',
    'eva_event_contact',
    'eva_event_details',
    'eva_events_categories_list',
    'eva_event_slider',
    'eva_slide_acoes',
    'eva_faqs',
    'eva_featured_event',
    'eva_featured_posts',
    'eva_featured_teacher',
    'eva_featured_video',
    'eva_featuredcourses',
    'eva_form_library',
    'eva_gallery',
    'eva_gallery_slider',
    'eva_globalsearch_n',
    'eva_globalsearch_sb',
    'eva_library_central',
    'eva_library_information',
    'eva_library_service',
    'eva_list_study_room',
    'eva_more_courses',
    'eva_my_courses',
    'eva_mynews',
    'eva_myorders',
    'eva_myviews',
    'eva_numbers',
    'eva_partners',
    'eva_pills',
    'eva_postgraduate_about',
    'eva_postgraduate_contact',
    'eva_postgraduate_services',
    'eva_publicidade',
    'eva_reports',
    'eva_reports_users',
    'eva_reports_users_controll',
    'eva_revistagu',
    'eva_services',
    'eva_services_dark',
    'eva_slide_acoes',
    'eva_slider_8',
    'eva_steps',
    'eva_subscribe',
    'eva_tablets',
    'eva_tabs',
    'eva_traning_suggestion',
    'eva_ts_controll',
    'eva_ts_view',
    'eva_tstmnls_3',
    'eva_users',
    'eva_users_slider',
    'eva_users_slider_round',
    'eva_video',
    'eva_video_pesquisa',
);
$ccnControlBlockListUri = $CFG->wwwroot . '/theme/evagu/ccn/visualize/ccn_block/jpeg/large/';
$ccnControlBlockListUriThumb = $CFG->wwwroot . '/theme/evagu/ccn/visualize/ccn_block/jpeg/thumb/';
$PAGE->requires->js_init_call('ccnCommentHandler', array(get_string('add_comment', 'theme_evagu')));
$PAGE->requires->js_init_call('ccnControl', array($ccnControlBlockListUri, $ccnControlBlockListUriThumb, $ccnLcVbCollection, $ccnMdlVersion));
$nav = $PAGE->flatnav;
$templatecontext['flatnavigation'] = $nav;
$templatecontext['firstcollectionlabel'] = $nav->get_collectionlabel();
if ($PAGE->pagetype == 'admin-setting-themesettingevagu') {
    $PAGE->requires->css('/theme/evagu/style/eva.editor.theme.css');
    $PAGE->requires->js('/theme/evagu/javascript/eva.editor.theme.js', true);
}
