<?php

namespace block_eva_cards_database\output;

defined('MOODLE_INTERNAL') || die;

use plugin_renderer_base;

class renderer extends plugin_renderer_base {


    public function render_cards_database(cards_database $database_cards)
    {
        return $this->render_from_template('block_eva_cards_database/cards', $database_cards->export_for_template($this)); // TODO: Change the autogenerated stub
    }

}
